name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install gitbook
        run: npm install -g gitbook-cli
      - name: Build gitbook
        run: |
          gitbook install
          gitbook build
      - name: Run stoat action
        uses: stoat-dev/stoat-action@v0
        if: always()
